services:
  database:
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      POSTGRES_DB: marketresearch
    # networks:
    #   - bridge
    ports:
      - "3452:5432"
    volumes:
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./src/database/staticData/staticData.sql:/docker-entrypoint-initdb.d/2_staticData.sql
      # - pgdata:/var/lib/postgresql/data
      # - ./extensions.sql:/docker-entrypoint-initdb.d/1_extensions.sql

volumes:
  pgdata:  
      

  #     services:
  # postgres:
  #   image: postgres:14.4
  #   command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
  #   volumes:
  #     - ./local/refreshDatabase.sql:/docker-entrypoint-initdb.d/4_refreshDatabase.sql
  #     - ./.env.local.sql:/docker-entrypoint-initdb.d/5_env.sql
  #   environment:
  #     POSTGRES_DB: gatherdev
  #     POSTGRES_PASSWORD: supersecret
  #   ports:
  #     - 5432:5432